services:
  task-manager:
    build: .
    image: task-manager:0.1
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  redis-populate:
    image: redis
    entrypoint: ["/redis-populate.sh","/redis-populate.txt"]
    depends_on:
      - redis
    env_file:
      - ./env.redis-populate
    volumes:
      - ./redis-populate.txt:/redis-populate.txt
      - ./redis-populate.sh:/redis-populate.sh
  redis:
    image: redis
    ports:
      - 6379:6379
