name: subscription-service

on:
  push:
    branches:
    - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Images
      run: |
        cd Chapter8
        docker compose -f docker-compose.yaml -f newsletter-lambda/docker-compose.yaml -f s3store-lambda/docker-compose.yaml -f sqs-to-lambda/docker-compose.yaml build 
      uses: actions/cache@v3
      with:
        path: /var/lib/docker/
        key: registry
    - name: Run application
      run: |
        cd Chapter8
        docker compose -f docker-compose.yaml -f newsletter-lambda/docker-compose.yaml -f s3store-lambda/docker-compose.yaml -f sqs-to-lambda/docker-compose.yaml up
      with:
        path: /var/lib/docker/
        key: registry